"""Deterministic tools the agent can call.

Financial numbers are never generated by an LLM: calculators and account
actions are plain, unit-tested Python so answers are exact and auditable.
Account tools run against a clearly-labelled demo customer (no real data).
"""
from __future__ import annotations

import itertools
import re
from datetime import date, timedelta

# --------------------------------------------------------------------------- #
# Number / slot extraction
# --------------------------------------------------------------------------- #
_NUM = r"(\d{1,3}(?:,\d{3})+|\d+(?:\.\d+)?)"
AMOUNT_RE = re.compile(r"\$\s?" + _NUM + r"\s*(k|m|million|thousand)?\b|" + _NUM + r"\s*(k|m|million|thousand)\b", re.I)
RATE_RE = re.compile(_NUM + r"\s*(%|percent|pct)", re.I)
YEARS_RE = re.compile(_NUM + r"[\s-]*(years?|yrs?|yr)\b", re.I)
MONTHS_RE = re.compile(_NUM + r"[\s-]*(months?|mos?)\b", re.I)
MONTHLY_RE = re.compile(r"\$\s?" + _NUM + r"\s*(k)?\s*(?:/|a|per|each|every)\s*(?:mo\b|month)", re.I)
BARE_NUM_RE = re.compile(r"(?<![\d.])" + _NUM + r"(?![\d.%])")

_MULT = {"k": 1e3, "thousand": 1e3, "m": 1e6, "million": 1e6}


def _to_float(s: str) -> float:
    return float(s.replace(",", ""))


def extract_slots(text: str) -> dict:
    """Pull amount / rate / term / monthly contribution out of free text."""
    slots: dict = {}
    t = text.lower()
    monthly = MONTHLY_RE.search(t)
    if monthly:
        slots["monthly"] = _to_float(monthly.group(1)) * (1e3 if monthly.group(2) else 1)
        t = t[: monthly.start()] + " " + t[monthly.end():]
    if m := RATE_RE.search(t):
        slots["rate"] = _to_float(m.group(1))
        t = t[: m.start()] + " " + t[m.end():]
    if m := YEARS_RE.search(t):
        slots["months"] = round(_to_float(m.group(1)) * 12)
        t = t[: m.start()] + " " + t[m.end():]
    elif m := MONTHS_RE.search(t):
        slots["months"] = round(_to_float(m.group(1)))
        t = t[: m.start()] + " " + t[m.end():]
    amounts = []
    for m in AMOUNT_RE.finditer(t):
        num, mult = (m.group(1), m.group(2)) if m.group(1) else (m.group(3), m.group(4))
        amounts.append(_to_float(num) * _MULT.get((mult or "").lower(), 1))
    if not amounts:
        amounts = [_to_float(n) for n in BARE_NUM_RE.findall(t) if _to_float(n) >= 100]
    if amounts:
        slots["amount"] = max(amounts)
    return slots


def money(x: float) -> str:
    return f"-${abs(x):,.2f}" if x < 0 else f"${x:,.2f}"


# --------------------------------------------------------------------------- #
# Calculators
# --------------------------------------------------------------------------- #
def loan_payment(amount: float, rate: float, months: int) -> dict:
    """Standard amortising loan payment (mortgage, auto, personal)."""
    r = rate / 100 / 12
    pay = amount / months if r == 0 else amount * r / (1 - (1 + r) ** -months)
    total = pay * months
    return {
        "monthly_payment": round(pay, 2),
        "total_paid": round(total, 2),
        "total_interest": round(total - amount, 2),
        "amount": amount,
        "rate": rate,
        "months": months,
    }


def savings_growth(monthly: float, rate: float, months: int, initial: float = 0.0) -> dict:
    """Future value with monthly contributions and monthly compounding."""
    r = rate / 100 / 12
    fv_initial = initial * (1 + r) ** months
    fv_contrib = monthly * months if r == 0 else monthly * (((1 + r) ** months - 1) / r)
    fv = fv_initial + fv_contrib
    contributed = initial + monthly * months
    return {
        "future_value": round(fv, 2),
        "contributed": round(contributed, 2),
        "interest_earned": round(fv - contributed, 2),
        "monthly": monthly,
        "initial": initial,
        "rate": rate,
        "months": months,
    }


def card_payoff(balance: float, apr: float, monthly: float) -> dict:
    """How long to pay off a credit-card balance with a fixed monthly payment."""
    r = apr / 100 / 12
    if monthly <= balance * r:
        return {"payable": False, "min_payment_needed": round(balance * r + 1, 2)}
    months, remaining, total = 0, balance, 0.0
    while remaining > 0.005 and months < 1200:  # exact month-by-month simulation
        remaining += remaining * r
        pay = min(monthly, remaining)
        remaining -= pay
        total += pay
        months += 1
    return {
        "payable": True,
        "months": months,
        "total_paid": round(total, 2),
        "total_interest": round(max(total - balance, 0), 2),
        "balance": balance,
        "apr": apr,
        "monthly": monthly,
    }


# --------------------------------------------------------------------------- #
# Demo account tools (mock core-banking system)
# --------------------------------------------------------------------------- #
_today = date.today()
DEMO_CUSTOMER = {
    "name": "Alex Morgan (demo customer)",
    "accounts": [
        {"type": "Everyday Checking", "last4": "4821", "balance": 2847.63},
        {"type": "High-Yield Savings", "last4": "9034", "balance": 15230.18},
        {"type": "Cash Back Card", "last4": "7712", "balance": -642.90, "credit_limit": 8000},
    ],
    "transactions": [
        {"date": str(_today - timedelta(days=0)), "desc": "Grocery Market #212", "amount": -86.42},
        {"date": str(_today - timedelta(days=1)), "desc": "Payroll Direct Deposit", "amount": 2450.00},
        {"date": str(_today - timedelta(days=2)), "desc": "Coffee House", "amount": -6.75},
        {"date": str(_today - timedelta(days=3)), "desc": "Electric Utility AutoPay", "amount": -118.20},
        {"date": str(_today - timedelta(days=4)), "desc": "Streaming Subscription", "amount": -15.99},
    ],
}
_ticket_ids = itertools.count(10421)


def get_balances() -> dict:
    return {"customer": DEMO_CUSTOMER["name"], "accounts": DEMO_CUSTOMER["accounts"]}


def recent_transactions(n: int = 5) -> dict:
    return {"transactions": DEMO_CUSTOMER["transactions"][:n]}


def lock_card(last4: str = "7712") -> dict:
    return {"status": "locked", "last4": last4, "reversible": True}


def create_ticket(summary: str, priority: str = "normal") -> dict:
    return {
        "ticket_id": f"FP-{next(_ticket_ids)}",
        "priority": priority,
        "summary": summary[:200],
        "eta": "within 1 business day" if priority == "normal" else "within 2 hours",
    }
